name: flutter_bloc_hive_login
description: A new Flutter project.


publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'


dependencies:
  flutter:
    sdk: flutter


  
  cupertino_icons: ^1.0.2
   #state managment
  flutter_bloc: ^8.1.1
  provider: ^6.0.4
  #cache
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  #http request
  dio: ^4.0.6
  json_annotation: ^4.7.0
  json_serializable: ^6.5.1
  build_runner: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

 
  flutter_lints: ^2.0.0
  #cache extra
  hive_generator: ^2.0.0
  


flutter:


  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  